name: Fixsy Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Create mock environment for CI
      run: cp .env.example .env

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze production code
      run: flutter analyze lib/

    - name: Build Web
      run: flutter build web --release
